import './globals.css'
import localFont from 'next/font/local'
import PageTransition from '@/components/page-transition'
import Lenis from '@/components/Lenis'
import Header from '@/components/header'
import Footer from '@/components/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const manrope = localFont({
  src: [
    {
      path: './fonts/manrope-latin-300-normal.woff2',
      weight: '300',
      style: 'light',
    },
    {
      path: './fonts/manrope-latin-400-normal.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/manrope-latin-500-normal.woff2',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/manrope-latin-600-normal.woff2',
      weight: '600',
      style: 'semibold',
    },
    {
      path: './fonts/manrope-latin-700-normal.woff2',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/manrope-latin-800-normal.woff2',
      weight: '800',
      style: 'extrabold',
    },
  ],
  display: 'swap',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Lenis>
        <body className={`$(manrope.className) min-h-screen overflow-hidden bg-gray-50 antialiased`}>
          <Header />
          <PageTransition>
            <main>{children}</main>
            <Footer />
          </PageTransition>
        </body>
      </Lenis>
    </html>
  )
}
